global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "smart_market_analyzer_api"
    static_configs:
      - targets: ["api:8001"]
    metrics_path: /metrics

  - job_name: "smart_market_analyzer_worker"
    static_configs:
      - targets: ["worker:8001"]
    metrics_path: /metrics